### ISSUE TITLE
Hi.where can i Buy this board.

### ISSUE THREAD

**Issue by giohomer** [Seeed-Studio/Tiny_BLE#1]
Hi where can i buy this board?
and where can i find the firmware?
I'm a student and i need to work with nrf51822 and MPU6050.
I have the nordic dev kit but i have some problem to work with TWI and soft device. Can you help me?

**Comment by yexiaobo-seeedstudio** [comment]
It will be online on Seeedstudio.com in Jan. And you can get more information in http://www.seeedstudio.com/wiki/BLE_Smurfs

**Comment by xiongyihui** [comment]
Hi, the board is available at http://www.seeedstudio.com/depot/Seeed-Tiny-BLE-BLE-6DOF-Mbed-Platform-p-2268.html now. You can try the MPU6050 library - http://developer.mbed.org/teams/Seeed/code/eMPL_MPU6050/  we used.
