### ISSUE TITLE
Extra pinouts

### ISSUE THREAD

**Issue by pandzorz** [Seeed-Studio/Tiny_BLE#3]
Hello,

I am working on a project at university, using a Tiny BLE board. I have been trying to find a clock output for use with a W25Q80BV as the serial clock, but unsure where I can pull this from on the board(e.g. SWCLK) and how to address that pin in my code.

Regards,
Andrew

**Comment by xiongyihui** [comment]
Unfortunately, the SWCLK can not be used as GPIO.
We are considering to design a new version of the Tiny BLE. It would be great to know your feedback of it.

**Comment by pandzorz** [comment]
Thanks for your reply. I feel that only 4 GPIO pins has been limiting for our project, and the ability to access the chip's clock value for serial clock syncing has been an issue as well, so they would be great to see on the chip. Additionally, more information for the pin names would be great, I had to look deep into the code to find the enum values for the board.

We're trying to use a 1MB flash storage chip over MISO/MOSI, but need a clock value from the chip. Is this possible at all? I've been trying to find somewhere in the schematic and board diagrams for this potential. Thanks for your time!

**Comment by xiongyihui** [comment]
Thanks for your feedback.
The pin information is as following.
![Pinout](https://github.com/Seeed-Studio/Tiny_BLE/raw/master/preview/tiny_ble_core.png)
The 4 available pins are p3-p6, all these pins can be used for analog, i2c or spi.
For example, p3 - miso, p4 - mosi, p5 -sck. The feature is IO flexible mapping.
