### ISSUE TITLE
Split board

### ISSUE THREAD

**Issue by jacarrasco** [Seeed-Studio/Tiny_BLE#4]
Hi,

I just receivied the TinyBLE i bought and i thought it would be splitted in two parts. I would like to test just the BLE part to test the antenna range. Could you please tell me the best way to do it? I mean how to split it and then beeing able to reunite to program it.

And a second thing. The current measurement can work alone in the BLE part?

Thank you,

**Comment by qunanan** [comment]
I think the simple way is you just split it .    : P

**Comment by xiongyihui** [comment]
1. Before splitting it, you'd better to program an OTA bootloader to the BLE part. See [nRF51 DFU bootloader](https://github.com/Seeed-Studio/nrf51_dfu_bootloader) and [nRF51822 OTA](https://developer.mbed.org/teams/Bluetooth-Low-Energy/wiki/Firmware-Over-the-Air-FOTA-Updates).

The SWDIO and SWCLK on the back of the BLE part can be also used to program it.
1. Yes, the CMSIS DAP interface part can be used standalone.
