### ISSUE TITLE
BLE part Battery

### ISSUE THREAD

**Issue by jacarrasco** [Seeed-Studio/Tiny_BLE#5]
Hi,
I have some questions that i cannot find.
First question, Is the battery in the BLE part rechargeable? 
Second question, i have been trying to enable the 3v3 pin in the BLE part. Following the schematic i found that the pin to activate would be the P30 in the nordic chip, am i right?
Third question. Following the Tiny BLE example code in mbed, it is supposed that when i press the BLE button SW1 (p17 in nordic chip) the blue led is supposed to blink, but actually, it only blinks when i press the SW2, the button that is in the CMSIS part, why?

Thank you,

**Comment by xiongyihui** [comment]
Hi Kazjako,
1. By default, the Tiny BLE doesn't contain a battery. It has a JST-1.0 battery connector.
2. Yes, the 3v3 pin is controlled by p30
3. pressing SW2 will reset the nordic chip, the SW1 button function is defined by your program.

**Comment by jacarrasco** [comment]
Hi xingyihui, 
I did some small modification of the tiny BLE and i wanted to assambly them using your seeed services. But i found that the following components are not included in the OPL list. Do you recommend something to assembly? Or could you add these components into the OPL list so we should be able do our own modification? The components not included in the OPL list are:
1   16MHz CRYSTAL'-2520'    2520    X1
1    AN2051 ANTENNA-2.4GHZ-0.5DBI'AN2051'   2P-SMD-L5.05_W.02_H1.07MM AN2051     ANT1 
1   HSMF-C118 LED-ARGB-4P-1210  LED-4P-1210-3.0X2.54    D1
1   XC6415 XC6415 USP-6C U3 Dual LDO Regulator with ON/OFF Switch 2 200R_1% R-0402    R29, R39
1    6.8R_1%    R-0603 R0603    R37
1   680mR_1%    R-0603 R0603    R36
1   BUTTON-4P   4P-SMD-L4.45_W3.22_H2.5MM   SW2
1   FDFMA2P853 FDFMA2P853    6P-SMD-W/-HEAT  Q3
1   JST 1.0 / 341023001 JACK-JST-2P-SMD-PW'1.0' JST-SMD-2P-1.0-90D  BAT
1   340005001   USB-MINIUSB-5P-MICRO MICRO-USB  J7

**Comment by xiongyihui** [comment]
It will be ok if these components are not in the OPL list. Please feel free to contact us (producer@seeed.cc)
